"""Add publish column

Revision ID: 3589a5e0bcc7
Revises: 
Create Date: 2023-02-03 10:24:19.917267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3589a5e0bcc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_publish', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panel', schema=None) as batch_op:
        batch_op.drop_column('is_publish')

    # ### end Alembic commands ###
